### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by Mailaender** [Return-To-The-Roots/s25edit#2]
I would like to package it for @openSUSE compare https://en.opensuse.org/Return_to_the_Roots

**Comment by Flow86** [comment]
Sure,
we still need to "combine" both projects (@Flamefire) and use cmake in this one, so it can be included into the rttr package

**Comment by Flamefire** [comment]
I'm working on a PR that will include this in the general rttr build, so the s25client and s25edit are next to each other. Almost done.
No separate package is required, this will be part of `Return to the roots` (especially due to the requirement that Game files need to be used and maps saved to the same folder as rttr)

**Comment by Flamefire** [comment]
Editor now in the main project. A release will follow once the build server is up and running again. Possibly after a port to C++11 to remove most of the boost deps.
